In [1]:
import numpy as np

In [12]:
#Array using lists
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr

array([[ 3,  6, 32,  7]])

In [4]:
myarr[0,1 ]

np.int64(6)

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr

array([[ 3,  6, 32,  7]])

In [8]:
#mainpulation
myarr[0,1] = 787983

In [9]:
myarr

array([[     3, 787983,     32,      7]])

In [11]:
myarr.dtype

dtype('int64')

Array creation convertion from python

In [13]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
listarray.dtype

dtype('int64')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [20]:
zeros = np.zeros((2,5))

In [21]:
zeros.shape

(2, 5)

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
rng = np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
lspace = np.linspace(1,4,4)

In [33]:
lspace

array([1., 2., 3., 4.])